id = "emmylua"
name = "EmmyLua"
description = "Lua use emmylua language server ."
version = "0.0.1"
schema_version = 1
authors = ["White Lee <lishjun01@126.com>"]
repository = "https://github.com/shijunLee/emmylua"
[language_servers.emmylua-analyzer-rust]
name = "emmylua-analyzer-rust"
languages = ["EmmyLua","Lua"]

[grammars.lua]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-lua"
commit = "99fc677e6971c425e8d407f59c77ab897e585c92"
